spring.application.name=coupleAi
app.frontend-base-url=${FRONTEND_URL:http://localhost:3000}
app.frontend-url=${FRONTEND_URL:${app.frontend-base-url}}

spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.url=jdbc:mysql://localhost:3306/beinema

spring.jpa.hibernate.ddl-auto=update

jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


metis.base-url=https://api.metisai.ir
metis.api-key=tpsg-KoyuR5CVfzKRIuadEBQS1qH1xthqIen